### PR TITLE
stabilize Privy tx flow, harden deploy targets, and align stack round UI

### LINKED ISSUE #27: Remove static and incorrect data
The contract doesn't save the total number of expected members. We need the total number of members when showing the stack goal => `deposit * member * member`.

Currently, the UI shows a placeholder (`DURATION` and `30 BREAD`).

Image

We want to show the correct data. To do this, we need to save the duration and member in the URL and local storage before creating the invite link.

Then update the invite page to show the stack duration and goal.

-----

The stack details page also shows incorrect data when the stack hasn't started. Now that we have the total members in localstorage, we can get the stack info from local storage to show the correct number of rounds (`member` = `rounds`).

Image

### LINKED ISSUE #30: Consensus decimal place
Round all decimals to 2 decimal places

### PR DESCRIPTION
**Pull request by franrolotti**
Closes: #30, Closes #27
## Summary
This PR combines the original local tx/deploy stability updates with additional fixes for deterministic local deploy behavior and round UI/action semantics.

## Includes
- Make `saving-circles` submodule branch configurable (default now: `feat/member-withdrawable-view`).
- Enable optimizer flags in deploy with configurable runs.
- Use unsponsored tx flow in local while keeping sponsorship in production.
- Route deposit `approve` + `deposit` through the same Privy tx path to avoid signer mismatch.

## Additional updates in this PR
- Prevent `make deploy` from unexpectedly changing contract versions:
  - remove implicit `forge install` from deploy.
  - add explicit `install-contract-deps` target.
- Update stack timing/action UI:
  - rename label to `Days left until current round ends`.
  - show deposit action based on real current-round eligibility (`canDeposit`), enabling coexistence with withdraw availability when both are valid.

### CODE REVIEW

File: makefile [hunk 1]
```diff
@@ -17,6 +17,8 @@ RPC_URL ?= http://localhost:8545
 PRIVATE_KEY ?= 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
 ADMIN_ADDRESS ?= 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
 OZ_UPGRADEABLE_REENTRANCY_COMMIT ?= 5c4c29275d02e06265ce1cfcad5a420b58a5ca02
+SAVING_CIRCLES_BRANCH ?= feat/member-withdrawable-view
```
Comment (Olaleye-Blessing) [inline makefile:20]: I think the default branch should be the stable branch. `dev` is the stable branch, yes?

We can then specify the branch we want to use locally.

```bash
make update-contract-submodules # pulls the stable branch
```

```bash
make update-contract-submodules feat/member-withdrawable-viewer # pulls the ongoing branch. It's not stable because it's been merged yet
```

wdyt?

File: src/hooks/use-sponsored-tx.ts [hunk 2]
```diff
@@ -1,17 +1,32 @@
...
+      {
+        ...options,
+        sponsor: false,
+        uiOptions: {
+          ...options?.uiOptions,
+          showWalletUIs: true,
+        },
+      }
     );
   };
```
Comment (Olaleye-Blessing) [inline src/hooks/use-sponsored-tx.ts]: What we had previously should work.

We sponsor gas in production.

We don't in development cause privy doesn't support 31337 (anvil's chainid)

**Review by Olaleye-Blessing — COMMENTED** [review]
I'll push some changes soon. You can pull and check if it works.
